### ISSUE TITLE
Convert variable_* to config_*

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/block_background_color#3]
Pretty simple module so should be easy to convert. Need an update hook, hook_config_info and default JSON file. Check https://api.backdropcms.org/converting-modules-from-drupal for specifics.

**Comment by keiserjb** [comment]
pr for this  https://github.com/backdrop-contrib/block_background_color/pull/8

**Comment by stpaultim** [comment]
Thanks for the PR. I've done some light testing and it seems to work good.
