### ISSUE TITLE
Update Maintainer in Readme file

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/block_background_color#4]
@nitheesh - Welcome to Backdrop CMS contrib group. 

Feel free to add yourself as maintainer. You may remove me if you like, or you can leave me as a  co-maintainer. I have enough to work on, so I'm good either way. Please, feel free to reach out to me at any time if you have questions or need help with anything.

**Comment by nitheesh** [comment]
Thanks, Tim. I've updated the Readme.
