### ISSUE TITLE
Downloading Updates Fails

### ISSUE THREAD

**Issue by Retsell** [backdrop-contrib/block_background_color#5]
HTTP error 404 occurred when trying to fetch https://github.com/backdrop-contrib/block_background_color/releases/download/1.x-1.0.1/block_background_color.zip.
**Downloading updates failed:**
Failed to download block_background_color from https://github.com/backdrop-contrib/block_background_color/releases/download/1.x-1.0.1/block_background_color.zip

Looks like the release URL is: https://github.com/backdrop-contrib/block_background_color/archive/1.x-1.0.1.zip?

**Comment by stpaultim** [comment]
How are you trying to download. I just went to the github page: 
https://github.com/backdrop-contrib/block_background_color and used the Download Zip link and it worked fine:

https://github.com/backdrop-contrib/block_background_color/archive/1.x-1.x.zip

This looks different from the links in your comment. 

NOTE: BackdropCMS.org is broken, so this module (and most contrib modules) can't be downloaded from there. See issue: https://github.com/backdrop-ops/backdropcms.org/issues/755

**Comment by Retsell** [comment]
Trying to Update the module on a site where the previous version was installed.  admin > modules > update >

block_background_color does have a link on the Modules page, and I see a similar thing happens for a new install.  I just assumed maybe the wrong links were put in, but maybe it is related to https://github.com/backdrop-ops/backdropcms.org/issues/755

**Comment by albanycomputers** [comment]
Just had the same problem...  tried downloading from within a website running1.20.1

![image](https://user-images.githubusercontent.com/1705388/139581570-42335009-891d-4851-b4a5-c2a7ba873633.png)

Same from backdropcms.org

![image](https://user-images.githubusercontent.com/1705388/139581605-d9b81744-6ade-4443-a004-df240715bee1.png)

But I could manually download from github.

**Comment by stpaultim** [comment]
Fixed.
